import type { Metadata } from "next";
import { Tinos, Inter } from "next/font/google";
import "./globals.css";

const tinos = Tinos({
  variable: "--font-tinos",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tinos.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
